// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: api/registry/history/v1/history.proto

package historyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistryKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	EnvironmentId string                 `protobuf:"bytes,2,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	RegistryId    string                 `protobuf:"bytes,3,opt,name=registry_id,json=registryId,proto3" json:"registry_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryKey) Reset() {
	*x = RegistryKey{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryKey) ProtoMessage() {}

func (x *RegistryKey) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryKey.ProtoReflect.Descriptor instead.
func (*RegistryKey) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{0}
}

func (x *RegistryKey) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RegistryKey) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *RegistryKey) GetRegistryId() string {
	if x != nil {
		return x.RegistryId
	}
	return ""
}

type Mutation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryId       string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Deleted       bool                   `protobuf:"varint,3,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mutation) Reset() {
	*x = Mutation{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutation) ProtoMessage() {}

func (x *Mutation) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutation.ProtoReflect.Descriptor instead.
func (*Mutation) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{1}
}

func (x *Mutation) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *Mutation) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Mutation) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type SubmitRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Key              *RegistryKey           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	RequestId        string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Mutations        []*Mutation            `protobuf:"bytes,5,rep,name=mutations,proto3" json:"mutations,omitempty"`
	Resolution       []byte                 `protobuf:"bytes,6,opt,name=resolution,proto3" json:"resolution,omitempty"`
	ExpectedRevision *uint64                `protobuf:"varint,7,opt,name=expected_revision,json=expectedRevision,proto3,oneof" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitRequest) GetKey() *RegistryKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SubmitRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SubmitRequest) GetMutations() []*Mutation {
	if x != nil {
		return x.Mutations
	}
	return nil
}

func (x *SubmitRequest) GetResolution() []byte {
	if x != nil {
		return x.Resolution
	}
	return nil
}

func (x *SubmitRequest) GetExpectedRevision() uint64 {
	if x != nil && x.ExpectedRevision != nil {
		return *x.ExpectedRevision
	}
	return 0
}

type Receipt struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestId         string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Revision          uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Status            string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Message           string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	PublishedRevision uint64                 `protobuf:"varint,5,opt,name=published_revision,json=publishedRevision,proto3" json:"published_revision,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{3}
}

func (x *Receipt) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Receipt) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Receipt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Receipt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Receipt) GetPublishedRevision() uint64 {
	if x != nil {
		return x.PublishedRevision
	}
	return 0
}

type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipt       *Receipt               `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitResponse) GetReceipt() *Receipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

type GetReceiptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *RegistryKey           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReceiptRequest) Reset() {
	*x = GetReceiptRequest{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiptRequest) ProtoMessage() {}

func (x *GetReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiptRequest.ProtoReflect.Descriptor instead.
func (*GetReceiptRequest) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{5}
}

func (x *GetReceiptRequest) GetKey() *RegistryKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetReceiptRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *RegistryKey           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Exact         bool                   `protobuf:"varint,3,opt,name=exact,proto3" json:"exact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{6}
}

func (x *GetRequest) GetKey() *RegistryKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetRequest) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *GetRequest) GetExact() bool {
	if x != nil {
		return x.Exact
	}
	return false
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *RegistryKey           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	AfterRevision uint64                 `protobuf:"varint,2,opt,name=after_revision,json=afterRevision,proto3" json:"after_revision,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{7}
}

func (x *ReadRequest) GetKey() *RegistryKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ReadRequest) GetAfterRevision() uint64 {
	if x != nil {
		return x.AfterRevision
	}
	return 0
}

func (x *ReadRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Candidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Resolution    []byte                 `protobuf:"bytes,4,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Mutations     []*Mutation            `protobuf:"bytes,6,rep,name=mutations,proto3" json:"mutations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{8}
}

func (x *Candidate) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Candidate) GetResolution() []byte {
	if x != nil {
		return x.Resolution
	}
	return nil
}

func (x *Candidate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Candidate) GetMutations() []*Mutation {
	if x != nil {
		return x.Mutations
	}
	return nil
}

type Version struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Revision        uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	ParentRevision  uint64                 `protobuf:"varint,2,opt,name=parent_revision,json=parentRevision,proto3" json:"parent_revision,omitempty"`
	Entries         []*Mutation            `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	Resolution      []byte                 `protobuf:"bytes,4,opt,name=resolution,proto3" json:"resolution,omitempty"`
	LegacyChangeset []byte                 `protobuf:"bytes,6,opt,name=legacy_changeset,json=legacyChangeset,proto3" json:"legacy_changeset,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{9}
}

func (x *Version) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Version) GetParentRevision() uint64 {
	if x != nil {
		return x.ParentRevision
	}
	return 0
}

func (x *Version) GetEntries() []*Mutation {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Version) GetResolution() []byte {
	if x != nil {
		return x.Resolution
	}
	return nil
}

func (x *Version) GetLegacyChangeset() []byte {
	if x != nil {
		return x.LegacyChangeset
	}
	return nil
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipts      []*Receipt             `protobuf:"bytes,1,rep,name=receipts,proto3" json:"receipts,omitempty"`
	NextRevision  uint64                 `protobuf:"varint,2,opt,name=next_revision,json=nextRevision,proto3" json:"next_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{10}
}

func (x *ListResponse) GetReceipts() []*Receipt {
	if x != nil {
		return x.Receipts
	}
	return nil
}

func (x *ListResponse) GetNextRevision() uint64 {
	if x != nil {
		return x.NextRevision
	}
	return 0
}

type RestoreRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Key              *RegistryKey           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	RequestId        string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TargetRevision   uint64                 `protobuf:"varint,5,opt,name=target_revision,json=targetRevision,proto3" json:"target_revision,omitempty"`
	ExpectedRevision *uint64                `protobuf:"varint,6,opt,name=expected_revision,json=expectedRevision,proto3,oneof" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{11}
}

func (x *RestoreRequest) GetKey() *RegistryKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RestoreRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RestoreRequest) GetTargetRevision() uint64 {
	if x != nil {
		return x.TargetRevision
	}
	return 0
}

func (x *RestoreRequest) GetExpectedRevision() uint64 {
	if x != nil && x.ExpectedRevision != nil {
		return *x.ExpectedRevision
	}
	return 0
}

type AppliedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *RegistryKey           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ReplicaId     string                 `protobuf:"bytes,2,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Revision      uint64                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppliedRequest) Reset() {
	*x = AppliedRequest{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppliedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppliedRequest) ProtoMessage() {}

func (x *AppliedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppliedRequest.ProtoReflect.Descriptor instead.
func (*AppliedRequest) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{12}
}

func (x *AppliedRequest) GetKey() *RegistryKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *AppliedRequest) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

func (x *AppliedRequest) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *AppliedRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VersionMeta struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Revision       uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	ParentRevision uint64                 `protobuf:"varint,2,opt,name=parent_revision,json=parentRevision,proto3" json:"parent_revision,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VersionMeta) Reset() {
	*x = VersionMeta{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionMeta) ProtoMessage() {}

func (x *VersionMeta) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionMeta.ProtoReflect.Descriptor instead.
func (*VersionMeta) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{13}
}

func (x *VersionMeta) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *VersionMeta) GetParentRevision() uint64 {
	if x != nil {
		return x.ParentRevision
	}
	return 0
}

type VersionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*VersionMeta         `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	NextRevision  uint64                 `protobuf:"varint,2,opt,name=next_revision,json=nextRevision,proto3" json:"next_revision,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionList) Reset() {
	*x = VersionList{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionList) ProtoMessage() {}

func (x *VersionList) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionList.ProtoReflect.Descriptor instead.
func (*VersionList) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{14}
}

func (x *VersionList) GetVersions() []*VersionMeta {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *VersionList) GetNextRevision() uint64 {
	if x != nil {
		return x.NextRevision
	}
	return 0
}

func (x *VersionList) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{15}
}

var File_api_registry_history_v1_history_proto protoreflect.FileDescriptor

const file_api_registry_history_v1_history_proto_rawDesc = "" +
	"\n" +
	"%api/registry/history/v1/history.proto\x12\x19wippy.registry.history.v1\"r\n" +
	"\vRegistryKey\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12%\n" +
	"\x0eenvironment_id\x18\x02 \x01(\tR\renvironmentId\x12\x1f\n" +
	"\vregistry_id\x18\x03 \x01(\tR\n" +
	"registryId\"U\n" +
	"\bMutation\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x18\n" +
	"\adeleted\x18\x03 \x01(\bR\adeleted\"\x9f\x02\n" +
	"\rSubmitRequest\x128\n" +
	"\x03key\x18\x01 \x01(\v2&.wippy.registry.history.v1.RegistryKeyR\x03key\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12A\n" +
	"\tmutations\x18\x05 \x03(\v2#.wippy.registry.history.v1.MutationR\tmutations\x12\x1e\n" +
	"\n" +
	"resolution\x18\x06 \x01(\fR\n" +
	"resolution\x120\n" +
	"\x11expected_revision\x18\a \x01(\x04H\x00R\x10expectedRevision\x88\x01\x01B\x14\n" +
	"\x12_expected_revisionJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05\"\xa5\x01\n" +
	"\aReceipt\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12-\n" +
	"\x12published_revision\x18\x05 \x01(\x04R\x11publishedRevision\"N\n" +
	"\x0eSubmitResponse\x12<\n" +
	"\areceipt\x18\x01 \x01(\v2\".wippy.registry.history.v1.ReceiptR\areceipt\"l\n" +
	"\x11GetReceiptRequest\x128\n" +
	"\x03key\x18\x01 \x01(\v2&.wippy.registry.history.v1.RegistryKeyR\x03key\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"x\n" +
	"\n" +
	"GetRequest\x128\n" +
	"\x03key\x18\x01 \x01(\v2&.wippy.registry.history.v1.RegistryKeyR\x03key\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x12\x14\n" +
	"\x05exact\x18\x03 \x01(\bR\x05exact\"\x84\x01\n" +
	"\vReadRequest\x128\n" +
	"\x03key\x18\x01 \x01(\v2&.wippy.registry.history.v1.RegistryKeyR\x03key\x12%\n" +
	"\x0eafter_revision\x18\x02 \x01(\x04R\rafterRevision\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"\xae\x01\n" +
	"\tCandidate\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\x12\x1e\n" +
	"\n" +
	"resolution\x18\x04 \x01(\fR\n" +
	"resolution\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12A\n" +
	"\tmutations\x18\x06 \x03(\v2#.wippy.registry.history.v1.MutationR\tmutationsJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04\"\xde\x01\n" +
	"\aVersion\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\x12'\n" +
	"\x0fparent_revision\x18\x02 \x01(\x04R\x0eparentRevision\x12=\n" +
	"\aentries\x18\x03 \x03(\v2#.wippy.registry.history.v1.MutationR\aentries\x12\x1e\n" +
	"\n" +
	"resolution\x18\x04 \x01(\fR\n" +
	"resolution\x12)\n" +
	"\x10legacy_changeset\x18\x06 \x01(\fR\x0flegacyChangesetJ\x04\b\x05\x10\x06\"s\n" +
	"\fListResponse\x12>\n" +
	"\breceipts\x18\x01 \x03(\v2\".wippy.registry.history.v1.ReceiptR\breceipts\x12#\n" +
	"\rnext_revision\x18\x02 \x01(\x04R\fnextRevision\"\xe6\x01\n" +
	"\x0eRestoreRequest\x128\n" +
	"\x03key\x18\x01 \x01(\v2&.wippy.registry.history.v1.RegistryKeyR\x03key\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12'\n" +
	"\x0ftarget_revision\x18\x05 \x01(\x04R\x0etargetRevision\x120\n" +
	"\x11expected_revision\x18\x06 \x01(\x04H\x00R\x10expectedRevision\x88\x01\x01B\x14\n" +
	"\x12_expected_revisionJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05\"\x9b\x01\n" +
	"\x0eAppliedRequest\x128\n" +
	"\x03key\x18\x01 \x01(\v2&.wippy.registry.history.v1.RegistryKeyR\x03key\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x02 \x01(\tR\treplicaId\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"R\n" +
	"\vVersionMeta\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\x12'\n" +
	"\x0fparent_revision\x18\x02 \x01(\x04R\x0eparentRevision\"\x91\x01\n" +
	"\vVersionList\x12B\n" +
	"\bversions\x18\x01 \x03(\v2&.wippy.registry.history.v1.VersionMetaR\bversions\x12#\n" +
	"\rnext_revision\x18\x02 \x01(\x04R\fnextRevision\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"\a\n" +
	"\x05Empty2\xd4\x06\n" +
	"\x0eHistoryService\x12]\n" +
	"\x06Submit\x12(.wippy.registry.history.v1.SubmitRequest\x1a).wippy.registry.history.v1.SubmitResponse\x12^\n" +
	"\n" +
	"GetReceipt\x12,.wippy.registry.history.v1.GetReceiptRequest\x1a\".wippy.registry.history.v1.Receipt\x12[\n" +
	"\fGetCandidate\x12%.wippy.registry.history.v1.GetRequest\x1a$.wippy.registry.history.v1.Candidate\x12W\n" +
	"\n" +
	"GetVersion\x12%.wippy.registry.history.v1.GetRequest\x1a\".wippy.registry.history.v1.Version\x12W\n" +
	"\x04List\x12&.wippy.registry.history.v1.ReadRequest\x1a'.wippy.registry.history.v1.ListResponse\x12^\n" +
	"\fListVersions\x12&.wippy.registry.history.v1.ReadRequest\x1a&.wippy.registry.history.v1.VersionList\x12U\n" +
	"\x05Watch\x12&.wippy.registry.history.v1.ReadRequest\x1a\".wippy.registry.history.v1.Version0\x01\x12_\n" +
	"\aRestore\x12).wippy.registry.history.v1.RestoreRequest\x1a).wippy.registry.history.v1.SubmitResponse\x12\\\n" +
	"\rReportApplied\x12).wippy.registry.history.v1.AppliedRequest\x1a .wippy.registry.history.v1.EmptyB>Z<github.com/wippyai/runtime/api/registry/history/v1;historyv1b\x06proto3"

var (
	file_api_registry_history_v1_history_proto_rawDescOnce sync.Once
	file_api_registry_history_v1_history_proto_rawDescData []byte
)

func file_api_registry_history_v1_history_proto_rawDescGZIP() []byte {
	file_api_registry_history_v1_history_proto_rawDescOnce.Do(func() {
		file_api_registry_history_v1_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_registry_history_v1_history_proto_rawDesc), len(file_api_registry_history_v1_history_proto_rawDesc)))
	})
	return file_api_registry_history_v1_history_proto_rawDescData
}

var file_api_registry_history_v1_history_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_registry_history_v1_history_proto_goTypes = []any{
	(*RegistryKey)(nil),       // 0: wippy.registry.history.v1.RegistryKey
	(*Mutation)(nil),          // 1: wippy.registry.history.v1.Mutation
	(*SubmitRequest)(nil),     // 2: wippy.registry.history.v1.SubmitRequest
	(*Receipt)(nil),           // 3: wippy.registry.history.v1.Receipt
	(*SubmitResponse)(nil),    // 4: wippy.registry.history.v1.SubmitResponse
	(*GetReceiptRequest)(nil), // 5: wippy.registry.history.v1.GetReceiptRequest
	(*GetRequest)(nil),        // 6: wippy.registry.history.v1.GetRequest
	(*ReadRequest)(nil),       // 7: wippy.registry.history.v1.ReadRequest
	(*Candidate)(nil),         // 8: wippy.registry.history.v1.Candidate
	(*Version)(nil),           // 9: wippy.registry.history.v1.Version
	(*ListResponse)(nil),      // 10: wippy.registry.history.v1.ListResponse
	(*RestoreRequest)(nil),    // 11: wippy.registry.history.v1.RestoreRequest
	(*AppliedRequest)(nil),    // 12: wippy.registry.history.v1.AppliedRequest
	(*VersionMeta)(nil),       // 13: wippy.registry.history.v1.VersionMeta
	(*VersionList)(nil),       // 14: wippy.registry.history.v1.VersionList
	(*Empty)(nil),             // 15: wippy.registry.history.v1.Empty
}
var file_api_registry_history_v1_history_proto_depIdxs = []int32{
	0,  // 0: wippy.registry.history.v1.SubmitRequest.key:type_name -> wippy.registry.history.v1.RegistryKey
	1,  // 1: wippy.registry.history.v1.SubmitRequest.mutations:type_name -> wippy.registry.history.v1.Mutation
	3,  // 2: wippy.registry.history.v1.SubmitResponse.receipt:type_name -> wippy.registry.history.v1.Receipt
	0,  // 3: wippy.registry.history.v1.GetReceiptRequest.key:type_name -> wippy.registry.history.v1.RegistryKey
	0,  // 4: wippy.registry.history.v1.GetRequest.key:type_name -> wippy.registry.history.v1.RegistryKey
	0,  // 5: wippy.registry.history.v1.ReadRequest.key:type_name -> wippy.registry.history.v1.RegistryKey
	1,  // 6: wippy.registry.history.v1.Candidate.mutations:type_name -> wippy.registry.history.v1.Mutation
	1,  // 7: wippy.registry.history.v1.Version.entries:type_name -> wippy.registry.history.v1.Mutation
	3,  // 8: wippy.registry.history.v1.ListResponse.receipts:type_name -> wippy.registry.history.v1.Receipt
	0,  // 9: wippy.registry.history.v1.RestoreRequest.key:type_name -> wippy.registry.history.v1.RegistryKey
	0,  // 10: wippy.registry.history.v1.AppliedRequest.key:type_name -> wippy.registry.history.v1.RegistryKey
	13, // 11: wippy.registry.history.v1.VersionList.versions:type_name -> wippy.registry.history.v1.VersionMeta
	2,  // 12: wippy.registry.history.v1.HistoryService.Submit:input_type -> wippy.registry.history.v1.SubmitRequest
	5,  // 13: wippy.registry.history.v1.HistoryService.GetReceipt:input_type -> wippy.registry.history.v1.GetReceiptRequest
	6,  // 14: wippy.registry.history.v1.HistoryService.GetCandidate:input_type -> wippy.registry.history.v1.GetRequest
	6,  // 15: wippy.registry.history.v1.HistoryService.GetVersion:input_type -> wippy.registry.history.v1.GetRequest
	7,  // 16: wippy.registry.history.v1.HistoryService.List:input_type -> wippy.registry.history.v1.ReadRequest
	7,  // 17: wippy.registry.history.v1.HistoryService.ListVersions:input_type -> wippy.registry.history.v1.ReadRequest
	7,  // 18: wippy.registry.history.v1.HistoryService.Watch:input_type -> wippy.registry.history.v1.ReadRequest
	11, // 19: wippy.registry.history.v1.HistoryService.Restore:input_type -> wippy.registry.history.v1.RestoreRequest
	12, // 20: wippy.registry.history.v1.HistoryService.ReportApplied:input_type -> wippy.registry.history.v1.AppliedRequest
	4,  // 21: wippy.registry.history.v1.HistoryService.Submit:output_type -> wippy.registry.history.v1.SubmitResponse
	3,  // 22: wippy.registry.history.v1.HistoryService.GetReceipt:output_type -> wippy.registry.history.v1.Receipt
	8,  // 23: wippy.registry.history.v1.HistoryService.GetCandidate:output_type -> wippy.registry.history.v1.Candidate
	9,  // 24: wippy.registry.history.v1.HistoryService.GetVersion:output_type -> wippy.registry.history.v1.Version
	10, // 25: wippy.registry.history.v1.HistoryService.List:output_type -> wippy.registry.history.v1.ListResponse
	14, // 26: wippy.registry.history.v1.HistoryService.ListVersions:output_type -> wippy.registry.history.v1.VersionList
	9,  // 27: wippy.registry.history.v1.HistoryService.Watch:output_type -> wippy.registry.history.v1.Version
	4,  // 28: wippy.registry.history.v1.HistoryService.Restore:output_type -> wippy.registry.history.v1.SubmitResponse
	15, // 29: wippy.registry.history.v1.HistoryService.ReportApplied:output_type -> wippy.registry.history.v1.Empty
	21, // [21:30] is the sub-list for method output_type
	12, // [12:21] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_registry_history_v1_history_proto_init() }
func file_api_registry_history_v1_history_proto_init() {
	if File_api_registry_history_v1_history_proto != nil {
		return
	}
	file_api_registry_history_v1_history_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_registry_history_v1_history_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_registry_history_v1_history_proto_rawDesc), len(file_api_registry_history_v1_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_registry_history_v1_history_proto_goTypes,
		DependencyIndexes: file_api_registry_history_v1_history_proto_depIdxs,
		MessageInfos:      file_api_registry_history_v1_history_proto_msgTypes,
	}.Build()
	File_api_registry_history_v1_history_proto = out.File
	file_api_registry_history_v1_history_proto_goTypes = nil
	file_api_registry_history_v1_history_proto_depIdxs = nil
}
