// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package historyv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion9

const (
	HistoryService_Submit_FullMethodName        = "/wippy.registry.history.v1.HistoryService/Submit"
	HistoryService_GetReceipt_FullMethodName    = "/wippy.registry.history.v1.HistoryService/GetReceipt"
	HistoryService_GetCandidate_FullMethodName  = "/wippy.registry.history.v1.HistoryService/GetCandidate"
	HistoryService_GetVersion_FullMethodName    = "/wippy.registry.history.v1.HistoryService/GetVersion"
	HistoryService_List_FullMethodName          = "/wippy.registry.history.v1.HistoryService/List"
	HistoryService_ListVersions_FullMethodName  = "/wippy.registry.history.v1.HistoryService/ListVersions"
	HistoryService_Watch_FullMethodName         = "/wippy.registry.history.v1.HistoryService/Watch"
	HistoryService_Restore_FullMethodName       = "/wippy.registry.history.v1.HistoryService/Restore"
	HistoryService_ReportApplied_FullMethodName = "/wippy.registry.history.v1.HistoryService/ReportApplied"
)

type HistoryServiceClient interface {
	Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error)
	GetReceipt(ctx context.Context, in *GetReceiptRequest, opts ...grpc.CallOption) (*Receipt, error)
	GetCandidate(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Candidate, error)
	GetVersion(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Version, error)
	List(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ListResponse, error)
	ListVersions(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*VersionList, error)
	Watch(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Version], error)
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*SubmitResponse, error)
	ReportApplied(ctx context.Context, in *AppliedRequest, opts ...grpc.CallOption) (*Empty, error)
}

type historyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHistoryServiceClient(cc grpc.ClientConnInterface) HistoryServiceClient {
	return &historyServiceClient{cc}
}

func (c *historyServiceClient) Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResponse)
	err := c.cc.Invoke(ctx, HistoryService_Submit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) GetReceipt(ctx context.Context, in *GetReceiptRequest, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, HistoryService_GetReceipt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) GetCandidate(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Candidate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Candidate)
	err := c.cc.Invoke(ctx, HistoryService_GetCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) GetVersion(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Version, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Version)
	err := c.cc.Invoke(ctx, HistoryService_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) List(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, HistoryService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) ListVersions(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*VersionList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionList)
	err := c.cc.Invoke(ctx, HistoryService_ListVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) Watch(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Version], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HistoryService_ServiceDesc.Streams[0], HistoryService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadRequest, Version]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HistoryService_WatchClient = grpc.ServerStreamingClient[Version]

func (c *historyServiceClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*SubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResponse)
	err := c.cc.Invoke(ctx, HistoryService_Restore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) ReportApplied(ctx context.Context, in *AppliedRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HistoryService_ReportApplied_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type HistoryServiceServer interface {
	Submit(context.Context, *SubmitRequest) (*SubmitResponse, error)
	GetReceipt(context.Context, *GetReceiptRequest) (*Receipt, error)
	GetCandidate(context.Context, *GetRequest) (*Candidate, error)
	GetVersion(context.Context, *GetRequest) (*Version, error)
	List(context.Context, *ReadRequest) (*ListResponse, error)
	ListVersions(context.Context, *ReadRequest) (*VersionList, error)
	Watch(*ReadRequest, grpc.ServerStreamingServer[Version]) error
	Restore(context.Context, *RestoreRequest) (*SubmitResponse, error)
	ReportApplied(context.Context, *AppliedRequest) (*Empty, error)
	mustEmbedUnimplementedHistoryServiceServer()
}

type UnimplementedHistoryServiceServer struct{}

func (UnimplementedHistoryServiceServer) Submit(context.Context, *SubmitRequest) (*SubmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedHistoryServiceServer) GetReceipt(context.Context, *GetReceiptRequest) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReceipt not implemented")
}
func (UnimplementedHistoryServiceServer) GetCandidate(context.Context, *GetRequest) (*Candidate, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCandidate not implemented")
}
func (UnimplementedHistoryServiceServer) GetVersion(context.Context, *GetRequest) (*Version, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedHistoryServiceServer) List(context.Context, *ReadRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedHistoryServiceServer) ListVersions(context.Context, *ReadRequest) (*VersionList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVersions not implemented")
}
func (UnimplementedHistoryServiceServer) Watch(*ReadRequest, grpc.ServerStreamingServer[Version]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedHistoryServiceServer) Restore(context.Context, *RestoreRequest) (*SubmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedHistoryServiceServer) ReportApplied(context.Context, *AppliedRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportApplied not implemented")
}
func (UnimplementedHistoryServiceServer) mustEmbedUnimplementedHistoryServiceServer() {}
func (UnimplementedHistoryServiceServer) testEmbeddedByValue()                        {}

type UnsafeHistoryServiceServer interface {
	mustEmbedUnimplementedHistoryServiceServer()
}

func RegisterHistoryServiceServer(s grpc.ServiceRegistrar, srv HistoryServiceServer) {
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HistoryService_ServiceDesc, srv)
}

func _HistoryService_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_Submit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).Submit(ctx, req.(*SubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_GetReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).GetReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_GetReceipt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).GetReceipt(ctx, req.(*GetReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_GetCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).GetCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_GetCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).GetCandidate(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).GetVersion(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).List(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_ListVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).ListVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_ListVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).ListVersions(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HistoryServiceServer).Watch(m, &grpc.GenericServerStream[ReadRequest, Version]{ServerStream: stream})
}

type HistoryService_WatchServer = grpc.ServerStreamingServer[Version]

func _HistoryService_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_ReportApplied_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppliedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).ReportApplied(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_ReportApplied_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).ReportApplied(ctx, req.(*AppliedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var HistoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wippy.registry.history.v1.HistoryService",
	HandlerType: (*HistoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _HistoryService_Submit_Handler,
		},
		{
			MethodName: "GetReceipt",
			Handler:    _HistoryService_GetReceipt_Handler,
		},
		{
			MethodName: "GetCandidate",
			Handler:    _HistoryService_GetCandidate_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _HistoryService_GetVersion_Handler,
		},
		{
			MethodName: "List",
			Handler:    _HistoryService_List_Handler,
		},
		{
			MethodName: "ListVersions",
			Handler:    _HistoryService_ListVersions_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _HistoryService_Restore_Handler,
		},
		{
			MethodName: "ReportApplied",
			Handler:    _HistoryService_ReportApplied_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _HistoryService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/registry/history/v1/history.proto",
}
